spring.profiles.active=dev
spring.application.name=auth-service
spring.config.import=optional:file:.env[.properties]

server.port=8081

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
cors.allowed-origins=*

eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
security.jwt.secret=${JWT_BASE64_SECRET}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
